/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intf;

import dise_lib_ms.DB_Connect;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.BorderFactory;

/**
 *
 * @author Hasintha Nayanajith
 */
public class ErrorFrame extends javax.swing.JFrame {

    /**
     * Creates new form ErrorFrame
     */
    public ErrorFrame() {
        initComponents();
        
        setIcon();
        
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(230,230,230)));
        
        
        
    }
    
    public void Error(String e){
    
        jTextArea2.setText(e);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        kButton1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Esoft Library | Warning Message");
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 7, 43));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 7, 43));
        kGradientPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Esoft Metro Campus");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(100, 10, 210, 40);

        jLabel24.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 204, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intf/icons8_warning64_64.png"))); // NOI18N
        kGradientPanel1.add(jLabel24);
        jLabel24.setBounds(20, 10, 60, 60);

        kButton3.setBackground(new java.awt.Color(0, 12, 19,0));
        kButton3.setText("OK");
        kButton3.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        kButton3.setkEndColor(new java.awt.Color(0, 102, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(0, 102, 204));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        kButton3.setkStartColor(new java.awt.Color(0, 102, 255));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton3);
        kButton3.setBounds(300, 240, 140, 30);

        jLabel34.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255,50)));
        kGradientPanel1.add(jLabel34);
        jLabel34.setBounds(20, 73, 420, 10);

        jLabel25.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 204, 255));
        jLabel25.setText("Library Management System");
        kGradientPanel1.add(jLabel25);
        jLabel25.setBounds(100, 40, 210, 30);

        kGradientPanel2.setBackground(new java.awt.Color(0, 7, 43));
        kGradientPanel2.setkBorderRadius(20);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255,50));
        kGradientPanel2.setkFillBackground(false);
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255,50));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(425, 100));
        kGradientPanel2.setLayout(null);

        jScrollPane2.setBorder(null);

        jTextArea2.setBackground(new java.awt.Color(0, 7, 43));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("FreeUniversal", 0, 13)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        kGradientPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 400, 100);

        kGradientPanel1.add(kGradientPanel2);
        kGradientPanel2.setBounds(20, 100, 420, 120);

        kButton1.setText("X");
        kButton1.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        kButton1.setkBorderRadius(0);
        kButton1.setkEndColor(new java.awt.Color(0, 7, 43));
        kButton1.setkForeGround(new java.awt.Color(204, 204, 204));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 51, 51));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        kButton1.setkStartColor(new java.awt.Color(0, 7, 43));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1);
        kButton1.setBounds(431, 0, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(465, 291));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed

        this.dispose();

    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErrorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErrorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErrorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErrorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ErrorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_warning_32.png")));
        
    }
}
